config/routes.rb
Rails.application.routes.draw do
  root "images#index"

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:show, :index]
  get 'profile' => 'users#profile'
  resources :images do
    resources :comments, except: [:index, :show]
  end
  get 'images/vote/:id', to: "images#vote", as: "images_vote"
  get 'images/downvote/:id', to: "images#downvote", as: "images_downvote"
  

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base

    belongs_to :image
    belongs_to :user
end

app/models/image.rb
class Image < ActiveRecord::Base

  has_attached_file :url, 
                  :styles => { :medium => "200x200"},
                  :default_url => "",
                  :convert_options => {:medium => '-background white -gravity center -extent 200x200'}

  # has_attached_file :url, :styles => {:thumb => "100x100>" }, 
  # :convert_options => {:thumb => "-gravity center -extent 100x100"}
  # validates_attachment_content_type :url, :content_type => /\Aimage\/.*\Z/

  has_many :comments
  belongs_to :user


end

app/models/user.rb
class User < ActiveRecord::Base


  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_image

  def new
    @comment = @image.comments.build
  end

  def create
    @comment = @image.comments.build(comments_params)
    if @comment.save
      redirect_to @image
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    if @comment.user != current_user
      redirect_to @image, notice: "Nope"
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comments_params)
      redirect_to @image, notice: "comment updated"
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user == current_user
      @comment.destroy
      redirect_to @image, notice: "comment deleted"
    else
      redirect_to @image, notice: "Nope"
    end
      render :back
    end 
  end

  # def edit
  #   @comment = Comment.edit(comments_params)
  # end

  # def update
  #   @comment = Comment.update(comments_params)
  #     redirect_to image_path(@image), :notice = "comment updated"
  # end

  def destroy
    @comment.destroy
    redirect_to :back, notice: "comment deleted"
  end


  private

  def set_image
    @image = Image.find(params[:image_id])
  end


  def comments_params
    params.require(:comment).permit(:body, :user_id, :image_id)
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_image, only: [:show, :edit, :update, :destroy, :vote, :downvote]
  def index
    @images = Image.all.order(vote: :desc)
    if params[:categories]
      @images = Image.where(categories: params[:categories])
    else
      @animals_images = Image.all.where(categories: "Animals").order(vote: :desc)
      
      @people_images = Image.all.where(categories: "People").order(vote: :desc)
      @landscape_images = Image.all.where(categories: "Landscapes").order(vote: :desc)
      @funny_images = Image.all.where(categories: "Funny").order(vote: :desc)
      @abstract_images = Image.all.where(categories: "Abstract").order(vote: :desc)
    end
  end

  def profile
    @images = current_user.Image
  end

  def show
    @image = Image.find(params[:id])
    @comment = @image.comments.build
    @comments = @image.comments.all
  end

  def new
    @categories = ["Animals", "People", "Landscapes", "Funny", "Abstract"]
    @image = Image.new
  end

  def create
    @categories = ["Animals", "People", "Landscapes", "Funny", "Abstract"]
    @image = Image.new(image_params)

    if @image.save
      redirect_to image_path(@image)
    else
      render :new
    end
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])

    if @image.update(image_params)
      redirect_to image_path
    else
      render :edit
    end
  end

  def vote
    @image = Image.find(params[:id])
    @image.vote += 1
    @image.save!
    redirect_to images_path
  end

  def downvote
    @image = Image.find(params[:id])
    @image.vote -= 1
    @image.save!
    redirect_to images_path
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to images_path
  end

  private

    def set_image
    @image = Image.find(params[:id])
  end

    def image_params
      params.require(:image).permit(:title, :url, :vote, :description, :categories, :user_id)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  private
 
  def sign_up_params
    params.require(:user).permit(:name, :bio, :email, :password, :password_confirmation)
  end
 
  def account_update_params
    params.require(:user).permit(:name, :bio, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def profile
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/comments/_form.html.erb
<%= bootstrap_form_for [@image, @comment] do |f| %>
  <%= f.text_area :body %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "Yeah Boy" %>
<% end %>
<h1> Add a new comment </h1>
<%= bootstrap_form_for [@image, @image.comments.build] do |f| %>
  <%= f.text_field :body %>

  <%#= f.hidden_field :user_id, value: current_user.id %>

  <%= f.submit "Send", class: "btn btn-primary" %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= render 'form' %>

app/views/comments/new.html.erb
<h1>Edit Comment</h1>
<%= render 'form' %>

app/views/images/edit.html.erb
<h1> Edit Picture </h1>
<%= bootstrap_form_for @image do |f| %>
  
  <%= f.text_field :title %>

  <%= f.text_field :url %>

  <%= f.text_field :vote %>

  <%= f.text_area :description %>

  <%#= f.hidden_field :user_id, value: current_user.id %>
  
  <%= f.submit "Post that sheeeaaat!", class: "btn btn-primary" %>
<% end %>

app/views/images/index.html.erb
<div class="container">

  <h1> Best Images </h1>
<%= link_to "Post a new pic!", new_image_path %>
<%#= render 'layouts/category' %>



<br>
<div class="firstRow">
<div class="row"> 
<% top_three = @animals_images.first(3) %>

  <% top_three.each do |img| %>
    <div class='col-md-3'>
        <h2><%= img.title %></h2>
        <h6><%= link_to image_tag(img.url), image_path(img) %></h6>
        <h3><%= img.categories %></h3>
        <h3><%= img.vote %></h3>
        <p><%= img.description %></p>
        <p><%= img.user_id %></p>
        <div class="upvotes">
        <%= link_to 'UpVote!', images_vote_path(img.id), :class => "btn btn-default btn-lg" %>
      </div>
      <div class="downvotes">
  <%= link_to 'DownVote!', images_downvote_path(img.id), :class => "btn btn-default btn-lg" %>
</div>
  <%= link_to "delete", img, method: :delete, :class => "btn btn-default btn-lg" %>
    </div>
    <%#= link_to 'Show Post', image_path(img) , :class => "btn anything" %>
  <%#= link_to 'Edit post', edit_image_path(img), :class => "btn btn-default btn-lg" %>
  <%#= link_to 'Destroy post', img, method: :delete, :class => "btn btn-default btn-lg" %>
  
    <% end %>
  <%# end %>
    
  </div>
</div>
<!--  -->
<br>
<div class="row"> 
<% top_three = @people_images.first(3) %>

  <% top_three.each do |img| %>
    <div class='col-md-3'>
        <h2><%= img.title %></h2>
        <h6><%= link_to image_tag(img.url), image_path(img) %></h6>
        <h3><%= img.categories %></h3>
        <h3><%= img.vote %></h3>
        <p><%= img.description %></p>
        <p><%= img.user_id %></p>
        <%= link_to 'UpVote!', images_vote_path(img.id), :class => "btn btn-default btn-lg" %>
  <%= link_to 'DownVote!', images_downvote_path(img.id), :class => "btn btn-default btn-lg" %>
<%= link_to "delete", img, method: :delete, :class => "btn btn-default btn-lg" %>  
    </div>
    <% end %>
  <%# end %>
    
  </div>
<!--  -->
<br>
<div class="row"> 
<% top_three = @landscape_images.first(3) %>

  <% top_three.each do |img| %>
    <div class='col-md-3'>
        <h2><%= img.title %></h2>
        <h6><%= link_to image_tag(img.url), image_path(img) %></h6>
        <h3><%= img.categories %></h3>
        <h3><%= img.vote %></h3>
        <p><%= img.description %></p>
        <p><%= img.user_id %></p>
        <%= link_to 'UpVote!', images_vote_path(img.id), :class => "btn btn-default btn-lg" %>
  <%= link_to 'DownVote!', images_downvote_path(img.id), :class => "btn btn-default btn-lg" %>
  <%= link_to "delete", img, method: :delete, :class => "btn btn-default btn-lg" %>
    </div>
    <% end %>
  <%# end %>
    
  </div>
<!--  -->
<br>
<div class="row"> 
<% top_three = @funny_images.first(3) %>

  <% top_three.each do |img| %>
    <div class='col-md-3'>
        <h2><%= img.title %></h2>
        <h6><%= link_to image_tag(img.url), image_path(img) %></h6>
        <h3><%= img.categories %></h3>
        <h3><%= img.vote %></h3>
        <p><%= img.description %></p>
        <p><%= img.user_id %></p>
        <%= link_to 'UpVote!', images_vote_path(img.id), :class => "btn btn-default btn-lg" %>
  <%= link_to 'DownVote!', images_downvote_path(img.id), :class => "btn btn-default btn-lg" %>
  <%= link_to "delete", img, method: :delete, :class => "btn btn-default btn-lg" %>
    </div>
    <% end %>
  <%# end %>
    
  </div>
<!--  -->

<br>
<div class="row"> 
<% top_three = @abstract_images.first(3) %>

  <% top_three.each do |img| %>
    <div class='col-md-3'>
        <h2><%= img.title %></h2>
        <h6><%= link_to image_tag(img.url), image_path(img) %></h6>
        <h3><%= img.categories %></h3>
        <h3><%= img.vote %></h3>
        <p><%= img.description %></p>
        <p><%= img.user_id %></p>
        <%= link_to 'UpVote!', images_vote_path(img.id), :class => "btn btn-default btn-lg" %>
  <%= link_to 'DownVote!', images_downvote_path(img.id), :class => "btn btn-default btn-lg" %>
  <%= link_to "delete", img, method: :delete, :class => "btn btn-default btn-lg" %>
    </div>
    <% end %>
  <%# end %>
    
  </div>
<!--  -->
</div>

app/views/images/new.html.erb
<div class="container">
<h1> New Picture </h1>
<%= bootstrap_form_for @image do |f| %>
  
  <%= f.text_field :title %>

  <%= f.file_field :url %>

  <%= f.radio_button :categories, "Animals" %>Animals
  <%= f.radio_button :categories, "People" %>People
  <%= f.radio_button :categories, "Landscapes" %>Landscapes
  <%= f.radio_button :categories, "Funny" %>Funny
  <%= f.radio_button :categories, "Abstract" %>Abstract
  

  <%= f.text_field :vote %>

  <%= f.text_area :description %>

  <%#= f.hidden_field :user_id, value: current_user.id %>

  <%= f.submit "Create Image", class: "btn btn-primary" %>
<% end %>
</div>

app/views/images/profile.html.erb
<h1>Images#profile</h1>
<p>Find me in app/views/images/profile.html.erb</p>

app/views/images/show.html.erb
<div class="container">

<%= link_to 'BACK', images_path, class: "btn btn-default" %>
<% if @image.user == current_user && user_signed_in? %>
  <%= link_to "EDIT", edit_image_path(@image), class: "btn btn-info"  %>
  <%= link_to "DELETE", @image, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"   %>
<% end %>


<%#= @image.title%> <%#= vote_path(@image) %>
<!-- <h4><%#= link_to @image.url, user_path(@link.user) %></h4> -->
<%= link_to "UPVOTE", images_vote_path(@image), class: "btn btn-success" %>
  <%= link_to "DOWNVOTE", images_downvote_path(@image), class: "btn btn-danger" %>

<!-- <h3>Posted by <%#= link_to (@image.user.name, user_path(@image.user) %></h3> -->
<!-- <h3>Posted by <%#= link_to @image.user.name, user_path(@image.user) %></h3> -->
<h2>
  Comments
  <%= link_to "Add Comment", new_image_comment_path(@image), class: "btn btn-primary" %>
</h2>

<% @image.comments.each do |comment| %>
  <blockquote>
    <p><%= comment.body %></p>
    <footer><%= comment.user.name %>
    <% if comment.user == current_user && user_signed_in? %>
      <%= link_to "EDIT", edit_image_comment_path(@image, comment) %>
      <%= link_to "DELETE", image_comment_path(@image, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    </footer>
    <% end %>
  </blockquote>
<% end %>
</div>
<%= link_to 'Back', images_path %>


<h3> Comments </h3>
<% @comments.each do |comment| %>
  <p> <%= comment.body %> </p>
 
 <%end%> 

<%= render 'comments/form'  %>


</div>

app/views/layouts/_category.html.erb
<ul class="no-bullet">
 <li>
  <%= link_to "All", images_path %>
  </li>
  <li>
  <%= link_to "Animals", images_path(categories: "Animals") %>
  </li>
  <li>
  <%= link_to "People", images_path(categories: "People") %>
  </li>
  <li>
  <%= link_to "Landscapes", images_path(categories: "Landscapes") %>
  </li>
  <li>
  <%= link_to "Funny", images_path(categories: "Funny") %>
  </li>
  <li>
  <%= link_to "Abstract", images_path(categories: "Abstract") %>
  </li>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Photo Wars", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <!-- We have an if statement here to only show the Users index link if users are signed in -->
        <% if user_signed_in? %>
          <li><%= link_to 'Users', users_path %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- This area is the title for the dropdown on the right hand side -->
            <!-- I set it up so if a user is logged in, it displays their name. Otherwise it just says account -->
            <% if user_signed_in? %>
              <%= current_user.name %>
            <% else %>
              Account
            <% end %>
             <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <!-- We have an if/else block here to show different links depending on if a user is signed in or not -->
            <% if user_signed_in? %>
              <li><%= link_to 'My Profile', profile_path %></li>
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete%></li>
            <% else %>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
              <li><%= link_to 'Sign In', new_user_session_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoWars</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar'  %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>
<% @users.each do |user| %>
<div class='well'>
  <h2><%= user.name %></h2>
  <h3><%= user.email %></h3>
  <p><%= user.bio %></p>
  <%= button_to 'Show', user_path(user), class: "btn btn-primary", method: :get %>
</div>
  <br />
<% end %>

app/views/users/profile.html.erb
<h1>My Profile</h1>
<h2><%= @user.name %></h2>
<h3><%= @user.email %></h3>
<p>
  <%= @user.bio %>
</p>

<%= button_to 'Edit Profile', edit_user_registration_path, class: "btn btn-primary", method: :get%>

<h3>My Links</h3>
<% @user.images.each do |img| %>
  <p><%= link_to img.title, image_path(img) %></p>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Profile</h1>
<h3><%= @user.email %></h3>
<p>
  <%= @user.bio %>
</p>

<h3><%= @user.name %>'s Links</h3>
<% @user.images.each do |img| %>
  <p><%= link_to img.title, image_path(img) %></p>
<% end %>